// All visible microcopy. MSL voice: declarative, calm, no exclamation, no emoji.
export const copy = {
  siteTitle: "Martha Stewart Living",
  siteSubtitle: "An Archive",
  tagline: "It is a good thing.",
  homeOpener: "A complete record of the episodes, with the recipes and the small good things they contained.",
  archive: "The archive",
  design: "The design",
  calendar: "The calendar",
  gaps: "What we don't know yet",
  viewArchive: "View the archive",
  episodeIndex: "An episode index",
  bySeason: "By season",
  byShow: "By show",
  begin: "Begin",
  readEpisode: "Read the episode",
  goodThings: "Good Things",
  bestIngredients: "Begin with the best ingredients.",
  notHere: "This page is not here.",
  return: "Return to the episode archive.",
  noEpisodes: "No episodes match these filters.",
  clearFilters: "Clear filters",
  sortBy: "Sort by",
  showLabel: "Show",
  seasonLabel: "Season",
  yearLabel: "Year",
  topicLabel: "Topic",
  themeLabel: "Theme",
  guestLabel: "Guest",
  tagLabel: "Tag",
  confidenceLabel: "Confidence",
  searchLabel: "Search",
  prev: "Previous",
  next: "Next",
  photographWanted: "Photograph wanted",
  imported: "Last imported",
  documented: "documented",
  recipes: "Recipes",
  guests: "Guests",
  topics: "Topics",
  themes: "Themes",
  tags: "Tags",
  sources: "Sources",
  segments: "Segments",
  notes: "Notes",
} as const;
